version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: dealflow
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dealflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    command: streamlit run app/streamlit_app.py --server.port 8501
    environment:
      DB_URL: postgresql+psycopg2://dealflow:secret@db:5432/dealflow
      COOKIE_KEY: "supersecretcookiekey"
    ports:
      - "8501:8501"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

volumes:
  pgdata:
